# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "08:00"
      timezone: Asia/Singapore
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: scope
    versioning-strategy: increase-if-necessary
    groups:
      pub-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "08:00"
      timezone: Asia/Singapore
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
