include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**

linter:
  rules:
    - directives_ordering
    - prefer_final_locals
    - unnecessary_final: false
    - prefer_final_fields
